apiVersion: apps/v1
kind: Deployment
metadata:
  name: academico-service
  namespace: sga
  labels:
    app: academico-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academico-service
  template:
    metadata:
      labels:
        app: academico-service
    spec:
      serviceAccountName: sga-serviceaccount
      containers:
        - name: academico
          image: emeday17/academico:1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8002
          env:
            - name: DB_HOST
              value: "mysql.sga.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: academico-service
  namespace: sga
spec:
  selector:
    app: academico-service
  ports:
    - name: http
      port: 8002
      targetPort: 8002
