apiVersion: v1
kind: Secret
metadata:
  name: admin-service-token
  namespace: eventos-peru
type: Opaque
data:
  # WARNING: This file previously contained a test token (base64).
  # Do NOT keep a hardcoded or test token here in production.
  # The admin service token MUST be a JWT signed with the cluster's JWT_SECRET
  # (or you should leave this secret absent so the gateway forwards the
  # incoming user's Authorization header for admin calls).
  # To create/apply a valid secret, run locally (example):
  # TOKEN=$(kubectl -n eventos-peru exec -it <iam-pod> -- python3 -c "import os,time,jwt;print(jwt.encode({'sub':'admin','iat':int(time.time()),'exp':int(time.time())+3600}, os.environ['JWT_SECRET'], algorithm='HS256'))")
  # kubectl -n eventos-peru create secret generic admin-service-token --from-literal=token="$TOKEN" --dry-run=client -o yaml | kubectl apply -f -
  token: ""